### ISSUE TITLE
Consider adding fusion and decay as submodules

### ISSUE THREAD

**Issue by spietras** [radio-aktywne/reactor#3]
But first research the potential drawbacks

**Comment by kpodsiad** [comment]
For sure, it would be easier to maintain default configuration if `decay` and `fusion` were included as submodules. Instead of the assumption that one has a proper directory structure (`decay` and `fusion` cloned next to `reactor`) we can leverage the fact that submodules are located in the `reactor` directory. Setup command would be simplified to:
```bash
git clone git@github.com:radio-aktywne/reactor.git && \
cd reactor && git submodule update --init && \
cd streaming && docker-compose up
```
Of course one will have to periodically fetch changes but it's still a very clear and production-friendly way to setup&run `reactor`

I am not sure if this change will affect the development process. Working with local, unpublished changes should be possible, and if not, it's very easy to provide overrides to zdocker-compose`.Everything should just work, I guess.
